[2024-09-10T08:22:41.005+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-10T08:22:41.087+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_V5.third_task scheduled__2024-02-13T00:00:00+00:00 [queued]>
[2024-09-10T08:22:41.111+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_V5.third_task scheduled__2024-02-13T00:00:00+00:00 [queued]>
[2024-09-10T08:22:41.113+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-10T08:22:41.212+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): third_task> on 2024-02-13 00:00:00+00:00
[2024-09-10T08:22:41.238+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=39820) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-10T08:22:41.244+0000] {standard_task_runner.py:72} INFO - Started process 39841 to run task
[2024-09-10T08:22:41.253+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_V5', 'third_task', 'scheduled__2024-02-13T00:00:00+00:00', '--job-id', '9190', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp29kq9s4s']
[2024-09-10T08:22:41.262+0000] {standard_task_runner.py:105} INFO - Job 9190: Subtask third_task
[2024-09-10T08:22:41.540+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_V5.third_task scheduled__2024-02-13T00:00:00+00:00 [running]> on host 5508ea9ebfaf
[2024-09-10T08:22:41.939+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='our_first_dag_V5' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-13T00:00:00+00:00'
[2024-09-10T08:22:41.940+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-10T08:22:41.989+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-10T08:22:41.990+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, this is the third task!']
[2024-09-10T08:22:42.007+0000] {subprocess.py:86} INFO - Output:
[2024-09-10T08:22:42.009+0000] {subprocess.py:93} INFO - hey, this is the third task!
[2024-09-10T08:22:42.011+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-10T08:22:42.068+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-10T08:22:42.070+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_V5, task_id=third_task, run_id=scheduled__2024-02-13T00:00:00+00:00, execution_date=20240213T000000, start_date=20240910T082241, end_date=20240910T082242
[2024-09-10T08:22:42.188+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-10T08:22:42.227+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-10T08:22:42.248+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
