[2024-09-12T02:20:19.204+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T02:20:19.313+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_V6.second_task scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2024-09-12T02:20:19.375+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_V6.second_task scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2024-09-12T02:20:19.379+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-12T02:20:19.644+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): second_task> on 2022-11-14 00:00:00+00:00
[2024-09-12T02:20:19.659+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6848) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-12T02:20:19.668+0000] {standard_task_runner.py:72} INFO - Started process 6873 to run task
[2024-09-12T02:20:19.665+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_V6', 'second_task', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '19864', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp6en0yg62']
[2024-09-12T02:20:19.669+0000] {standard_task_runner.py:105} INFO - Job 19864: Subtask second_task
[2024-09-12T02:20:19.808+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_V6.second_task scheduled__2022-11-14T00:00:00+00:00 [running]> on host 5508ea9ebfaf
[2024-09-12T02:20:20.173+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='acap' AIRFLOW_CTX_DAG_ID='our_first_dag_V6' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2022-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-11-14T00:00:00+00:00'
[2024-09-12T02:20:20.190+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T02:20:20.251+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-12T02:20:20.254+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, this is the second task!']
[2024-09-12T02:20:20.278+0000] {subprocess.py:86} INFO - Output:
[2024-09-12T02:20:20.282+0000] {subprocess.py:93} INFO - hey, this is the second task!
[2024-09-12T02:20:20.283+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-12T02:20:20.381+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T02:20:20.391+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_V6, task_id=second_task, run_id=scheduled__2022-11-14T00:00:00+00:00, execution_date=20221114T000000, start_date=20240912T022019, end_date=20240912T022020
[2024-09-12T02:20:20.455+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-12T02:20:20.491+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-12T02:20:20.509+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
