[2024-09-10T08:11:53.764+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-10T08:11:53.825+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_V5.third_task scheduled__2021-12-12T00:00:00+00:00 [queued]>
[2024-09-10T08:11:53.870+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_V5.third_task scheduled__2021-12-12T00:00:00+00:00 [queued]>
[2024-09-10T08:11:53.873+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-10T08:11:53.941+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): third_task> on 2021-12-12 00:00:00+00:00
[2024-09-10T08:11:53.964+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=30052) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-10T08:11:53.970+0000] {standard_task_runner.py:72} INFO - Started process 30061 to run task
[2024-09-10T08:11:53.973+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_V5', 'third_task', 'scheduled__2021-12-12T00:00:00+00:00', '--job-id', '6805', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpb30u8chd']
[2024-09-10T08:11:53.981+0000] {standard_task_runner.py:105} INFO - Job 6805: Subtask third_task
[2024-09-10T08:11:54.085+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_V5.third_task scheduled__2021-12-12T00:00:00+00:00 [running]> on host 5508ea9ebfaf
[2024-09-10T08:11:54.329+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='our_first_dag_V5' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2021-12-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-12-12T00:00:00+00:00'
[2024-09-10T08:11:54.330+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-10T08:11:54.367+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-10T08:11:54.370+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, this is the third task!']
[2024-09-10T08:11:54.384+0000] {subprocess.py:86} INFO - Output:
[2024-09-10T08:11:54.390+0000] {subprocess.py:93} INFO - hey, this is the third task!
[2024-09-10T08:11:54.391+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-10T08:11:54.451+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-10T08:11:54.452+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_V5, task_id=third_task, run_id=scheduled__2021-12-12T00:00:00+00:00, execution_date=20211212T000000, start_date=20240910T081153, end_date=20240910T081154
[2024-09-10T08:11:54.544+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-10T08:11:54.575+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-10T08:11:54.584+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
