[2024-09-27T01:16:15.356+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-27T01:16:15.377+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v02.get_sklearn scheduled__2024-09-26T00:00:00+00:00 [queued]>
[2024-09-27T01:16:15.389+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v02.get_sklearn scheduled__2024-09-26T00:00:00+00:00 [queued]>
[2024-09-27T01:16:15.430+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-27T01:16:15.534+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): get_sklearn> on 2024-09-26 00:00:00+00:00
[2024-09-27T01:16:15.554+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=180) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-27T01:16:15.559+0000] {standard_task_runner.py:72} INFO - Started process 192 to run task
[2024-09-27T01:16:15.587+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v02', 'get_sklearn', 'scheduled__2024-09-26T00:00:00+00:00', '--job-id', '22751', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmpwp95xrgy']
[2024-09-27T01:16:15.589+0000] {standard_task_runner.py:105} INFO - Job 22751: Subtask get_sklearn
[2024-09-27T01:16:15.861+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_python_dependencies_v02.get_sklearn scheduled__2024-09-26T00:00:00+00:00 [running]> on host ced43fa3e256
[2024-09-27T01:16:16.722+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v02' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2024-09-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-26T00:00:00+00:00'
[2024-09-27T01:16:16.726+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-27T01:16:22.558+0000] {logging_mixin.py:190} INFO - scikit-learn with version: 1.5.2
[2024-09-27T01:16:22.559+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-27T01:16:22.568+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-27T01:16:22.569+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_python_dependencies_v02, task_id=get_sklearn, run_id=scheduled__2024-09-26T00:00:00+00:00, execution_date=20240926T000000, start_date=20240927T011615, end_date=20240927T011622
[2024-09-27T01:16:22.615+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-27T01:16:22.637+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-27T01:16:22.641+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
