[2024-09-12T02:19:19.331+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T02:19:19.345+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_V6.second_task scheduled__2022-08-12T00:00:00+00:00 [queued]>
[2024-09-12T02:19:19.354+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_V6.second_task scheduled__2022-08-12T00:00:00+00:00 [queued]>
[2024-09-12T02:19:19.355+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-12T02:19:19.371+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): second_task> on 2022-08-12 00:00:00+00:00
[2024-09-12T02:19:19.378+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5671) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-12T02:19:19.379+0000] {standard_task_runner.py:72} INFO - Started process 5673 to run task
[2024-09-12T02:19:19.378+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_V6', 'second_task', 'scheduled__2022-08-12T00:00:00+00:00', '--job-id', '19577', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpjhec1zsk']
[2024-09-12T02:19:19.381+0000] {standard_task_runner.py:105} INFO - Job 19577: Subtask second_task
[2024-09-12T02:19:19.427+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_V6.second_task scheduled__2022-08-12T00:00:00+00:00 [running]> on host 5508ea9ebfaf
[2024-09-12T02:19:19.510+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='acap' AIRFLOW_CTX_DAG_ID='our_first_dag_V6' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2022-08-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-12T00:00:00+00:00'
[2024-09-12T02:19:19.511+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T02:19:19.525+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-12T02:19:19.526+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, this is the second task!']
[2024-09-12T02:19:19.533+0000] {subprocess.py:86} INFO - Output:
[2024-09-12T02:19:19.534+0000] {subprocess.py:93} INFO - hey, this is the second task!
[2024-09-12T02:19:19.535+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-12T02:19:19.558+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T02:19:19.559+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_V6, task_id=second_task, run_id=scheduled__2022-08-12T00:00:00+00:00, execution_date=20220812T000000, start_date=20240912T021919, end_date=20240912T021919
[2024-09-12T02:19:19.595+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-12T02:19:19.610+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-12T02:19:19.614+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
