[2024-09-18T00:30:07.927+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-18T00:30:07.978+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_api_v04.get_name scheduled__2024-09-16T00:00:00+00:00 [queued]>
[2024-09-18T00:30:07.991+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_api_v04.get_name scheduled__2024-09-16T00:00:00+00:00 [queued]>
[2024-09-18T00:30:08.022+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-18T00:30:08.152+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): get_name> on 2024-09-16 00:00:00+00:00
[2024-09-18T00:30:08.228+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=237) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-18T00:30:08.253+0000] {standard_task_runner.py:72} INFO - Started process 266 to run task
[2024-09-18T00:30:08.288+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_api_v04', 'get_name', 'scheduled__2024-09-16T00:00:00+00:00', '--job-id', '21952', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_taskflow_api.py', '--cfg-path', '/tmp/tmpvji4r0dv']
[2024-09-18T00:30:08.413+0000] {standard_task_runner.py:105} INFO - Job 21952: Subtask get_name
[2024-09-18T00:30:08.951+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_taskflow_api_v04.get_name scheduled__2024-09-16T00:00:00+00:00 [running]> on host 5508ea9ebfaf
[2024-09-18T00:30:11.149+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_taskflow_api_v04' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2024-09-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-16T00:00:00+00:00'
[2024-09-18T00:30:11.178+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-18T00:30:11.184+0000] {python.py:240} INFO - Done. Returned value was: {'first_name': 'Jerry', 'last_name': 'fauzi'}
[2024-09-18T00:30:11.502+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-18T00:30:11.548+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_taskflow_api_v04, task_id=get_name, run_id=scheduled__2024-09-16T00:00:00+00:00, execution_date=20240916T000000, start_date=20240918T003007, end_date=20240918T003011
[2024-09-18T00:30:11.909+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-18T00:30:12.150+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-18T00:30:12.222+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
