[2024-09-12T02:21:31.331+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T02:21:31.366+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_V6.second_task scheduled__2023-03-04T00:00:00+00:00 [queued]>
[2024-09-12T02:21:31.386+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_V6.second_task scheduled__2023-03-04T00:00:00+00:00 [queued]>
[2024-09-12T02:21:31.388+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-12T02:21:31.425+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): second_task> on 2023-03-04 00:00:00+00:00
[2024-09-12T02:21:31.450+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=8227) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-12T02:21:31.453+0000] {standard_task_runner.py:72} INFO - Started process 8244 to run task
[2024-09-12T02:21:31.448+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_V6', 'second_task', 'scheduled__2023-03-04T00:00:00+00:00', '--job-id', '20195', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp6i3_zg4x']
[2024-09-12T02:21:31.458+0000] {standard_task_runner.py:105} INFO - Job 20195: Subtask second_task
[2024-09-12T02:21:31.610+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_V6.second_task scheduled__2023-03-04T00:00:00+00:00 [running]> on host 5508ea9ebfaf
[2024-09-12T02:21:31.862+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='acap' AIRFLOW_CTX_DAG_ID='our_first_dag_V6' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2023-03-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-04T00:00:00+00:00'
[2024-09-12T02:21:31.866+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T02:21:31.901+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-12T02:21:31.907+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, this is the second task!']
[2024-09-12T02:21:31.921+0000] {subprocess.py:86} INFO - Output:
[2024-09-12T02:21:31.923+0000] {subprocess.py:93} INFO - hey, this is the second task!
[2024-09-12T02:21:31.924+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-12T02:21:31.974+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T02:21:31.976+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_V6, task_id=second_task, run_id=scheduled__2023-03-04T00:00:00+00:00, execution_date=20230304T000000, start_date=20240912T022131, end_date=20240912T022131
[2024-09-12T02:21:32.056+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-12T02:21:32.107+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-12T02:21:32.113+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
